[general]
import = [
    "~/.config/alacritty/themes/themes/rose_pine.toml"
]

[font]
size = 15.0

[font.normal]
family = "Iosevka Nerd Font Mono"
#family = "ComicShannsMono Nerd Font"
style = "Regular"


[font.bold]
family = "Iosevka Nerd Font Mono"
style = "Bold"

[font.italic]
family = "Iosevka Nerd Font Mono"
style = "Italic"

[font.bold_italic]
family = "Iosevka Nerd Font Mono"
style = "Bold Italic"
